[en]
    languageName = "English"
    contentDir = "content"
    weight = 1
    [en.params.head]
        tagline = "Ann Catherine Jose"
    [en.params.social]
        title = "Connect with me"
        caption = "We can collaborate on interesting projects, participate in hackathons, or discuss the latest in technology."
    [en.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
